### PR TITLE
Updates for Symphony 2.4 (perhaps earlier?)

### PR DESCRIPTION
**Pull request by brendo**
Hey Brock, 

Just using DTG in a new project with Symphony 2.4 so here's a couple of updates to get things working again. The biggest change is that you can have multiple DTG's in a Section now :)

There is probably more commits to add, but just thought I'd open the PR early incase there are others who need them.

Cheers,

Brendan

### CODE REVIEW

**Comment by brockpetrie** [comment]
Thanks, dude! The multiple instances fix is huge!

**Comment by brendo** [comment]
No worries, definitely not the prettiest of fixes but I needed it for a project so just made it happen!

**Comment by andrewminton** [comment]
Just spotted this!! winning! :)

**Comment by andrewminton** [comment]
This has so much potential as a Dynamic Field. Craft CMS style approach to content, like Rowans Content Field.

**Pull request merged**
