### PR TITLE
Added extension.meta.xml

### PR DESCRIPTION
**Pull request by nickdunn**
Hi Brock,

I took the liberty of adding the new extension meta file to document this extension. Once merged you'll be able to sign in to http://symphonyextensions.com and add the extension to the site.

### CODE REVIEW

**Comment by nickdunn** [comment]
Ah, go on :-)

**Comment by nickdunn** [comment]
Out of interest, would you like me to update this extension for Symphony 2.3?

**Comment by nickdunn** [comment]
There are some quite big changes — I think Stage is now in the core, there are some big styling changes, and a load of classes/methods that have changed too.

**Comment by nilshoerrmann** [comment]
> I think Stage is now in the core …

It's not. But the Duplicator has been updated so it could be used as a replacement for Stage – but the functionality is still different. And so is the look.

**Comment by brockpetrie** [comment]
Hey Nick, I'm really sorry I haven't gotten back to you!

Thanks for taking the time to do this, I appreciate it. I finally have some time to play around with Symphony 2.3, so I'll try and make some headway in getting this up-to-date in the coming weeks.

**Comment by nickdunn** [comment]
No worries, thanks for the update :-) Saw you added the repo to the site — nice one! Archived Filter too?

**Pull request merged**
